export enum NotificationType {
  ORDER_STATUS = 'ORDER_STATUS',
  PROMOTIONAL = 'PROMOTIONAL',
  SYSTEM = 'SYSTEM',
  PAYMENT_STATUS = 'PAYMENT_STATUS',
  SHIPPING_UPDATE = 'SHIPPING_UPDATE',
  NEW_PRODUCT = 'NEW_PRODUCT',
}
