export enum HttpMessage {
  OK = 'Request was successful.',
  CREATED = 'Resource created successfully.',
  NO_CONTENT = 'No content available.',
  BAD_REQUEST = 'Bad request.',
  UNAUTHORIZED = 'Unauthorized request.',
  FORBIDDEN = 'Forbidden access.',
  NOT_FOUND = 'Resource not found.',
  INTERNAL_SERVER_ERROR = 'Internal server error.',
  SERVICE_UNAVAILABLE = 'Service unavailable.',
  REGISTER_SUCCESS = 'Đăng ký thành công',
  VERIFY_OTP_SUCCESS = 'Xác thực thành công',
  RESEND_OTP_SUCCESS = 'Gửi lại OTP thành công',
  LOGIN_SUCCESS = 'Đăng nhập thành công',
  LOGOUT_SUCCESS = 'Đăng xuất thành công',
  GET_USER_ERROR = 'Lấy thông tin người dùng thất bại',
}
